* Chapitre I - Concepts et outils de base

** 1 - Énergies caractéristiques

*** 1.1 Énergie thermique
- Pour T=1K, k_B*T \approx 0.1 meV

*** 1.2 Énergie de Fermi

*** 1.3 Différence d'énergie entre deux états quantique voisins

*** 1.4 Énergie de confinement

*** 1.5 Énergie de charge

*** 1.6 Énergie associée au désordre

*** 1.7 Énergie associée au champs magnétique
- Énergie Zeeman
- Énergie de cyclotron

** 2 - Longueurs caractéristiques

*** 2.1 Taille du système

*** 2.2 Longueur de Fermi
\lambda_F = 2*\pi / K_F  ~  distance inter-electrons moyenne

*** 2.3 Libre parcours moyen: L_m
Distance moyenne parcourue par un e- avant que son *impulsion change* en raison d'une collision.

**** Diffusion élastique:
E inchangé.

**** Diffusion inélastique:
E changé. (ex: e--phonon, e--e-)
Se fait de plus en plus rare quand T diminue:
     une collision inélastique == un "perte" d'énergie du e- (conversion).
     a T=0, l'e- ne peut pas baisser son énergie, donc il n'y a pas de collision inélastiques.

**** Diffusion avec des diffuseurs ayant des degrés de liberté internes (élastique ou inélastique).
ex: impuretés magnétiques 


*** 2.4 Longueur de déphasage L_{\phi}
Distance moyenne parcourue par un e- avant que sa *phase quantique soit rendue aléatoire*.
== Distance moyenne qu'un e- parcours dans un temps \tau_{\phi}
L_{\phi} > L_m

Interféromètre => déphasage induit par le chemin suivi

La diffusion élastique ne produit pas de déphasage.


*** 2.5 Longueur magnétique


*** 2.6 Quelques valeurs numériques

** 3 - Transport semi-classique
*** 3.1 Conductivité classique
Newton pour un e- dans un champs éléctrique uniforme:
m a = force éléctrique - force de friction
m dV/dt = -eE - Vm/\tau_m
Régime stationnaire -> V = vitesse de dérive 

densité de courant j = \sigma E
    où sigma = n_e e^2 \tau_m / m  <- formule de Drude
      la conductivité

*** 3.2 

* Chapitre II - c
