#+OPTIONS: ^:{}
* Chapitre I - Concepts et outils de base

** 1 - Énergies caractéristiques
*** 1.1 Énergie thermique
- Pour T=1K, k_B*T \approx 0.1 meV

*** 1.2 Énergie de Fermi

*** 1.3 Différence d'énergie entre deux états quantique voisins

*** 1.4 Énergie de confinement

*** 1.5 Énergie de charge

*** 1.6 Énergie associée au désordre

*** 1.7 Énergie associée au champs magnétique
- Énergie Zeeman
- Énergie de cyclotron
h_bar w_c avec w_c = eB/m


** 2 - Longueurs caractéristiques
*** 2.1 Taille du système

*** 2.2 Longueur de Fermi
\lambda_F = 2*\pi / K_F  ~  distance inter-electrons moyenne

*** 2.3 Libre parcours moyen: L_m
Distance moyenne parcourue par un e- avant que son *impulsion change* en raison d'une collision.

**** Diffusion élastique:
E inchangé.

**** Diffusion inélastique:
E changé. (ex: e--phonon, e--e-)
Se fait de plus en plus rare quand T diminue:
     une collision inélastique == un "perte" d'énergie du e- (conversion).
     a T=0, l'e- ne peut pas baisser son énergie, donc il n'y a pas de collision inélastiques.

**** Diffusion avec des diffuseurs ayant des degrés de liberté internes (élastique ou inélastique).
ex: impuretés magnétiques 


*** 2.4 Longueur de déphasage L_{\phi}
Distance moyenne parcourue par un e- avant que sa *phase quantique soit rendue aléatoire*.
== Distance moyenne qu'un e- parcours dans un temps \tau_{\phi}
L_{\phi} > L_m

Interféromètre => déphasage induit par le chemin suivi

La diffusion élastique ne produit pas de déphasage.


*** 2.5 Longueur magnétique


*** 2.6 Quelques valeurs numériques


** 3 - Transport semi-classique
*** 3.1 Conductivité classique (Drude)
Newton pour un e- dans un champs éléctrique uniforme:
m a = force éléctrique - force de friction
m dV/dt = -eE - Vm/\tau_m
Régime stationnaire -> V = vitesse de dérive 

densité de courant \vec{j} = \sigma E
    où sigma = n_e e^2 \tau_m / m  <- formule de Drude
      la conductivité *classique*

*** 3.2 Conductivité semi-classique (Équation de Boltzmann)

densité de courant dans un cristal:
  \vec{j} = -e/Volume x somme sur les vecteurs d'ondes et les bandes
    de \vec{v}_{K,n} g_{K,n}
  avec g l'occupation de l'état |\vec{K},n>

- À l'équilibre: g_{K,n} suis l'occupation de Fermi-Dirac:
    g = f = 1 / [exp(\beta E_{K,n} - \mu) + 1)]
    avec mu le potential chimique
  [[https://www.desmos.com/calculator/mrkwlptxoe][fermi-dirac]]

  on a aussi \vec{j} = 0 lorsque le cristal respecte la symmétrie par inversion
      du temps. (démo: E_{K,n} fonction paire en K,
      g_{K,n} (car à l'équilibre donc = fermi-dirac) et v_{K,n} impaires 
                  -> rien ne survie à la somme.)

- Hors équilibre: g_{*K*,n} suis l'équation de Boltzman:
    ...
    avec *ṙ* = *r*_{*K*,n}  + +terme courbur de Berry+


*** 3.3 Courant de dérive (E>0) (matrice de conductivité)

On résout l'équation de Boltzmann pour E uniforme et B = 0
Le résultat sera l'occupation g_{K,n} en fonction de E.
Puis on pourra trouver \vec{j} (première eq de 3.2)

Par approche perturbative, g = f + \delta f
  -> dans la partie droite: (f+\delta f) - f  = \delta f
...
On arrive à une expression pour le courant:
j_alpha = sigma_{alpha beta} E_beta  (somme sur beta)

avec \sigma le *tenseur conductivité*,
    = e^2/V somme sur les vevcteur d'onde et les couches
        ( v_Kn^alpha v_Kn^beta tau_Kn (-dr f_kn / dr E_kn) )

diférent de la formule de Drude.

*** 3.4 Courant de diffusion (E=0) (matrice de diffusion) (relation d'Einstein)
On suppose
- pas de force sur les e-: \point{\vec{K}} = 0  (\vec{E}=0)
- rien ne dépend du temps
- f_{\vec{K}, n} n'est plus uniforme -> gradient de densité d'e-

en résolvant l'équation de Boltzmann on obtient \delta{f} que l'on remplace
dans l'expression de j (3.2) et on trouve le courant de diffusion:
j_\alpha = e D_{\alpha\beta} dn_e / dr_{\beta}

et D_{alpha beta} = sigma_{alpha beta}/ (e² dn_e/dmu)  <- relation d'Einstein
le tenseur de diffusion
    mu le potentiel chimique

i) Basse température (régime dégénéré) et mu = epsilon_F
       la densité n_e = 1/V * somme d'heavyside (epsilon_F - E_kn)
       dn_e / d epsilon_F = 1/V * somme de delta de Dirac = rho(epsilon_F)
       -> rho la densité d'états par unité de volume
    => D_ab = sigma_ab / (e² rho(epsilon_F))

ii) régime non dégénéré:
    n_e = 1/V somme de distribution Maxwell-Boltzmann
    on obtient D_ab = sigma_ab * kBT / (e² n_e)

*** 3.5 Courant total (dérive + diffusion)
On trouve que j_tot = 1/e matrice sigma dr/dr\vec{r} (mu - eV)
avec mu le potentiel chimique et donc
(mu - eV) le potentiel electrochimique
Alors, le courant avec cette approche semi-classique est proportionnel
au gradient du potentiel electrochimique par la matrice de diffusion / e.

*** 3.6 Cas spécial GE3D à T=0 (retrouve Drude)
Avec l'approximation qu'une seule bande interesecte epsilon_F
que E est isotrope
    (càd que E_{\vec{K} n} = E_K  (module de K))
alors
    sigma = e² tau_{epsilon_F} n_e / m

    la formule de Drude !


*** Exercice: Magnétoconductivité dans un GE2D
E en x et y, B en z, statiques et uniformes
Approche perturbative, on trouve 
(i) la conductivité longitudinale diminue quand B augmente
(ii) quand B suffisament grand (1T), sont effet devient significatif dans
    la conductivité:
    matrice sigma = σ_0 / (1 + (ω_c tau)² * ((1 τω_c)
                                             (τω_c 1))

    avec ω_c la pulsation de cyclotron = eB/m

** 4 - GE2D

*** 4.1 Diagramme de bandes (GaAs-AlGaAs)
    
  
*** 4.2 Fonction d'onde et densité d'états
Approximation puis triangulaire.
    
** 5 - Matrice denstié

